### ISSUE TITLE
Really helpful 

### ISSUE THREAD

**Issue by spacesudo** [Sentientech/solana-py-implementation#3]
This is really helpful and of great help to me.
I would love to know if there's a way to include metadata to a token created using solanapy? Like adding a name, ticker, and description etc...

**Comment by SeveighTech-Management** [comment]
I am not sure.
The way I did mine, if I remember correctly, was I used [Dexlab](https://www.dexlab.space/mintinglab/spl-token) to update the metadata

I'm sure there may be a way. I took a little detour and was learning how to write smart contracts on Ethereum but I'm coming back to Solana so I should figure that out soon, if you don't figure it out on your own by then.

**Comment by spacesudo** [comment]
Thanks
