### ISSUE TITLE
How to set parameters program_id and mint ?

### ISSUE THREAD

**Issue by chiwalfrm** [Sentientech/solana-py-implementation#4]
Confused about how to set these two lines

program_id = "<token_program_id>" #eg: https://solscan.io/token/FpekncBMe3Vsi1LMkh6zbNq8pdM6xEbNiFsJBRcPbMDQ | FpekncBMe3Vsi1LMkh6zbNq8pdM6xEbNiFsJBRcPbMDQ
mint = "<token_address>" #eg: https://solscan.io/account/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA | TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA

Specifically I want to send USDC which has mint address EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.  Does this go on the first line or the second?  what would the other parameter be set to?

**Comment by chiwalfrm** [comment]
For USDC, use this:

program_id = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" #eg: https://solscan.io/account/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA | TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" #eg: https://solscan.io/token/FpekncBMe3Vsi1LMkh6zbNq8pdM6xEbNiFsJBRcPbMDQ | FpekncBMe3Vsi1LMkh6zbNq8pdM6xEbNiFsJBRcPbMDQ

Note that the example.py has it backwards.  TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA goes with program_id and not mint

**Comment by SeveighTech-Management** [comment]
You're right!
Thanks for pointing that out!
