### ISSUE TITLE
Unable to Verify Token Account

### ISSUE THREAD

**Issue by leftkats** [Sentientech/solana-py-implementation#5]
**Description:**

I am encountering an issue while trying to run the code. The problem arises specifically on the line where I attempt to verify the token address. Here's the snippet of the code:

https://github.com/seveightech/solana-py-implementation/blob/1af44a3512d4959c0e1624f8ebdc157fb738f282/example.py#L22

**Error Messages:**
When verifying the token wallet:
- "Account not found" and after printing the Exception [here](https://github.com/seveightech/solana-py-implementation/blob/1af44a3512d4959c0e1624f8ebdc157fb738f282/solana_simplified.py#L46) I get "Invalid account size"

**Additional Information:**
- I tried also to verify the main wallet address and getting the following
"Account not found" and after printing the Exception [here](https://github.com/seveightech/solana-py-implementation/blob/1af44a3512d4959c0e1624f8ebdc157fb738f282/solana_simplified.py#L46) I get "Invalid account owner"

- The following line of code https://github.com/seveightech/solana-py-implementation/blob/1af44a3512d4959c0e1624f8ebdc157fb738f282/example.py#L21 produced a valid token address same with that from spl-token cli.
- Could you also provide an example of how the private key looks like and how I can obtain it? This information would be helpful for troubleshooting and understanding the setup requirements.

**Comment by SeveighTech-Management** [comment]
I think this video will give you a fair idea of what to look for:
https://www.youtube.com/watch?v=mKJKIgTJ6LY

The private key you use should belong to the same wallet that is used to create the token.
